nameEndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: Deploy Sphinx build
        push: origin gh-pages --set-upstream --force
        add: '*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
